pipeline {
    agent {
        label 'AGENT-1'  // this is the Label which we mentioned while configuring the Jenkins agent and this pipeline gets exected, when these both the values match
    }
     environment {
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "324512687633"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
     }
     options {
            timeout(time: 30, unit: 'MINUTES')  // this shows max time to run a pipeline
            disableConcurrentBuilds()   // this disables the parallel builds and used mostly in PROD pipelines
            ansiColor('xterm')   // to enable the colurs in the console output
             }  
     parameters {
        string(name: 'appVersion', description: 'Image version of the application')  // version of the image
        choice(name: 'deploy_to', choices: ['dev', 'qa', 'prod'], description: 'Pick the Environment')  // this displays in which env we are deploying
                }        
    stages {
        stage('Deploy') {  // this stage is to deploy into K8s
            steps {
                script {
                    dir('catalogue-deployment')  {// line no-30&31 These commands replace the placeholder IMAGE_VERSION in the environment-specific Helm values file with the given application version, then perform a Helm upgrade (or install if not already deployed) of the specified component into the target Kubernetes namespace using that updated values file.
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {  // kubectl must be installed on Jenkins Agent and AWS creds must be configured in Jenkins Master
                        sh """
                            aws eks update-kubeconfig --region $REGION --name "$PROJECT-${params.deploy_to}"
                            kubectl get nodes
                            sed -i "s/IMAGE_VERSION/${params.appVersion}/g" values-${params.deploy_to}.yaml   
                            helm upgrade --install $COMPONENT -f values-${params.deploy_to}.yaml -n $PROJECT . 
                        """
                    }
                    }
                }
            }
        }
        stage('Check Status') { // this stage is to see, whether the deployment is deployed or not, if not we will rollback to the previous version, if we doing it for the first time, it will tell the status
            steps {
                script {
                    dir('catalogue-deployment'){
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        def deploymentStatus = sh(returnStdout: true, script: "kubectl rollout status deployment/catalogue --timeout=30s -n $PROJECT || echo FAILED").trim()
                        if (deploymentStatus.contains("successfully rolled out")){
                            echo "Deployment is success"
                        }
                        else {
                            sh """
                                helm rollback $COMPONENT -n $PROJECT
                                sleep 20
                               """
                        def rollbackStatus = sh(returnStdout: true, script: "kubectl rollout status deployment/catalogue --timeout=30s -n $PROJECT || echo FAILED").trim()
                        if (rollbackStatus.contains("successfully rolled out")) {
                            error "Deployment is Failure, Rollback Success"
                        }
                        else{
                            error "Deployment is Failure, Rollback Failure. Application is not running"
                        }
                }
                }
                    }  
                }
            }
        }
    }
}