pipeline {
    agent {
        label 'AGENT-1'
    }
    environment {
        REGION = "us-east-1"
        ACC_ID = "324512687633"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
        APP_VERSION = ''  // Will be overridden in stage
    }
    parameters {
        booleanParam(
            name: 'deploy',
            defaultValue: false,
            description: 'Check this box to trigger catalogue-deployment after successful build'
        )
    }
    options {
        timeout(time: 30, unit: 'MINUTES')  // this shows max time to run a pipeline
        disableConcurrentBuilds()   // this disables the parallel builds and used mostly in PROD pipelines
        ansiColor('xterm')   // to enable the colurs in the console output
    }
    stages {
        stage('Read package.json') {  // this stage is to get the appVersion from the package.json file
            steps {
                script {
                    def pkgPath = 'catalogue/package.json'
                    def packageJson = readJSON file: pkgPath
                    def version = packageJson.version

                    echo "Package version: ${version}"

                    // Save to environment for use in all later stages
                    env.APP_VERSION = version
                }
            }
        }
        stage('Unit Testing'){
            steps {
                dir('catalogue')
                script {
                     sh """
                            echo "unit tests"
                     """
                }
            }
        }
        stage('Sonar Scan'){   // sonar Scanning
            environment {
                    scannerHome = tool 'sonar-8.0.1'  // name of the scanner which we mentioned in our Jenkins
                }
            steps {
                dir('catalogue')
                script {
                    // Sonar Server envrionment
                    withSonarQubeEnv(installationName: 'sonar-8.0.1') {  // name of the scanner which we mentioned in our Jenkins
                            sh "${scannerHome}/bin/sonar-scanner"
                    }
                }

            }
        }
        stage('Installing Dependencies') {  // this stage is to install the dependencies
            steps {
                dir('catalogue') {
                    sh 'npm install'
                }
            }
        }

        stage('Docker Build') {   // what ever we mentioned inside this stage are the commmands given in the AWS ECR itself, but we have to modify little according to our project
            steps {
                dir('catalogue') {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com
                            docker build -t ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${env.APP_VERSION} .
                            docker push ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${env.APP_VERSION}
                        """
                    }
                }
            }
        }

        stage('Trigger Deploy') {   // This will trigger the catalogue deployment 
            when {
                expression { params.deploy == true }  // or just { params.deploy } if boolean
            }
            steps {
                dir('catalogue-deployment') {
                    build job: 'catalogue-deployment',
                    parameters: [
                        string(name: 'appVersion', value: "${env.APP_VERSION}"),
                        string(name: 'deploy_to', value: 'dev')
                    ],
                    propagate: false,  // even catalogue-deployment fails, catalogue will not be effected
                    wait: false // catalogue will not wait for catalogue-deployment pipeline completion
                }
            }
        }
    }

    post {
        always {
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success {
            echo 'Hello Success'
        }
        failure {
            echo 'Hello Failure'
        }
    }
}