pipeline {
    agent {
        label 'AGENT-1'
    }
     environment { 
        appVersion = ''
     }
    stages {
        stage('Read package.json') {
            steps {
                sh 'ls -l'
                script {
                def packageJson = readJSON file: 'package.json'
                appVersion = packageJson.version
                echo "Package version: ${appVersion}"
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}